// Auto generated file, do not tamper
#ifdef INCLUDE_CONFIG_HEADER
#ifndef _CONFIG_HEADER_H
#define _CONFIG_HEADER_H
#define CONFIG_SPYBOT_CONTROLLER
#define ARCH_STM32
#define PROC_STM32F1
#define CONFIG_SPYBOT_APP_MASTER
#define CONFIG_SPYBOT_VIDEO
#define CONFIG_SPYBOT_JOYSTICK
#define CONFIG_SPYBOT_XBUTTONS
#define CONFIG_SPYBOT_XLEDS
#define STM32F10X_MD
#define USE_STDPERIPH_DRIVER
#define USER_HARDFAULT
#define CONFIG_MEMOPS
#define CONFIG_VARCALL
#define CONFIG_MATH
#define CONFIG_MINIUTILS
#define CONFIG_TASK_QUEUE
#define CONFIG_RINGBUFFER
#define CONFIG_GPIO
#define CONFIG_UART
#define CONFIG_SPI
#define CONFIG_SPI_DEVICE
#define CONFIG_I2C
#define CONFIG_I2C_DEVICE
#endif
#endif
